deep_diagnose/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'deep_diagnose'

urlpatterns = [
    # url('/', views.redirecting, name='redirecting'),
    url(r'^register/', views.register, name='register'),
    # /home/
    # for finding nearby companies
    url(r'^home/$', views.home, name='find'),


    # /
    # /company/id(1,2..)
    # giving company details like tests and their price
    url(r'^company/(?P<pk>[0-9]+)/$', views.CompanyDetails.as_view(), name='company_detail'),

    # /test_list/
    # for list of all tests
    url(r'^test_list/$', views.TestList.as_view(), name='test_list'),

    # /result/
    # shows result according to users location
    url(r'^result/$', views.result, name='result'),

    # /test/pk(1,2 ..)
    # for test details like about_test companies offering that test with price
    url(r'^tests/(?P<pk>[0-9]+)/$', views.TestDetail.as_view(), name='tests_detail'),

    url(r'^response/$', views.put_list, name='response'),

    path('response1/<str:abc>', views.show_results),

    path('profile/', views.profile, name='profile'),

    path('ordernow/(?P<pk>[0-9]+)', views.OrderNow, name='ordernow'),

    path('thankyou/', views.thankyou, name='thankyou'),

    url(r'test/add/$', views.TestCreate.as_view(), name='test-add'),

    url(r'test/update/(?P<pk>[0-9]+)/$', views.TestUpdate.as_view(), name='test-update'),

    url(r'test/(?P<pk>[0-9]+)/delete/$', views.TestDelete.as_view(), name='test-delete'),

    url(r'company/(?P<pk>[0-9]+)/delete/$', views.CompanyDelete.as_view(), name='company-delete'),


    url(r'^admin_test_list/$', views.AdminTestList.as_view(), name='admin_test_list'),

    url(r'^admin_company_list/$', views.AdminCompanyList.as_view(), name='admin_company_list'),

    path('adminhome/', views.adminhome, name='adminhome'),

    url(r'^login-admin/$', views.loginAdminPanel, name='admin-login'),

    path('adminprofile/', views.adminprofile, name='admin-profile'),

    path('company/', views.CompanyList.as_view(), name='companylist'),

    url(r'category(?P<pk>[0-9]+)/$', views.Category.as_view(), name='category'),

    path('orderhistory/', views.OrderHistory, name='orderhistory'),
    url(r'order/(?P<pk>[0-9]+)/cancel/$', views.CancelOrder.as_view(), name='cancel-order'),
    url(r'order/(?P<pk>[0-9]+)/update/$', views.OrderUpdate.as_view(), name='update-order'),

    url(r'^search',views.search_titles),#renders ajax_search.html
]

deepdiagnoses/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('deep_diagnose.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'),
         name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
    path('auth/', include('social_django.urls', namespace='social')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

deep_diagnose/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class CompanyDetail(models.Model):
    company_name = models.CharField(max_length=250, unique=True)
    email_id = models.EmailField(unique=True)
    contact_no = models.CharField(max_length=12)
    address_line1 = models.CharField(max_length=125)
    city = models.CharField(max_length=125)
    state = models.CharField(max_length=125)
    logo = models.ImageField(upload_to='logo')

    def __str__(self):
        return str(self.company_name)


class TestCategory(models.Model):
    category = models.CharField(max_length=125)

    def __str__(self):
        return str(self.category)


class Meta:
    verbose_name = 'TestCategory'
    verbose_name_plural = 'TestCategory'


class Tests(models.Model):
    test_name = models.CharField(max_length=125)
    category = models.ForeignKey(TestCategory, on_delete=models.CASCADE,null=True)

    def __str__(self):
        return str(self.test_name)

    class Meta:
        verbose_name = 'Tests'
        verbose_name_plural = 'Tests'


class CompanyTests(models.Model):
    company_name = models.ForeignKey(CompanyDetail, on_delete=models.CASCADE)
    tests = models.ForeignKey(Tests, on_delete=models.CASCADE)
    cost = models.IntegerField(default=0)

    def __str__(self):
        return str(self.company_name)

    class Meta:
        verbose_name_plural = 'CompanyTests'


class OrderInfo(models.Model):
    order_no = models.AutoField(primary_key=True)
    company_name = models.CharField(max_length=125, default='NULL')
    test_name = models.CharField(max_length=125, default='NULL')
    user_name = models.CharField(max_length=125)
    email_id = models.EmailField()
    age = models.CharField(max_length=20)
    address_line_1 = models.CharField(max_length=125)
    city = models.CharField(max_length=125)
    state = models.CharField(max_length=125)
    zip_code = models.CharField(max_length=20)
    phone_no = models.CharField(max_length=12)
    suitable_date = models.CharField(max_length=12)
    suitable_time = models.CharField(max_length=12)


class Company(models.Model):
    company = models.CharField(max_length=100)
    password = models.CharField(max_length=100)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

deep_diagnose/views.py
from .filters import CompanyFilter
from django.views import generic
from .models import CompanyDetail, Tests,  CompanyTests, OrderInfo, TestCategory,Profile
from django.shortcuts import render, HttpResponseRedirect, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from . forms import UserRegistrationForm,LoginForm, UserUpdateForm, ProfileUpdateForm, OrderNowForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django import forms
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail


# def redirecting(request):
#     return redirect('/home/',)


# register user
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            userObj = form.cleaned_data
            username = userObj['username']
            email = userObj['email']
            password = userObj['password']
            if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
                User.objects.create_user(username, email, password)
                user = authenticate(username=username, password=password)
                login(request, user)
                return HttpResponseRedirect('/home')
            else:
                raise forms.ValidationError('Looks like a username with that email or password already exists')
    else:
        form = UserRegistrationForm()
    return render(request, 'deep_diagnose/register.html', {'form': form})


# for finding companies in a particular area
def home(request):
    return render(request, 'deep_diagnose/user_location.html')


# user profile
@login_required
def profile(request):
    return render(request, 'deep_diagnose/profile.html')


# admin login
def loginAdminPanel(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            account = authenticate(username=username, password=password)
            if account is not None:
                login(request, account)
                #here is redirecting to admin panel
                return HttpResponseRedirect('/adminhome/')
            else:
                return render(request, 'registration/adminlogin.html')
        else:
            return render(request, 'registration/adminlogin.html')
    else:
        form = LoginForm()
        context = {'form':form}
        return render(request, 'registration/adminlogin.html', context)


# first page for admin
@login_required
def adminhome(request):
    return render(request,'admin/adminhome.html')


# admin profile
@login_required
def adminprofile(request):
    return render(request, 'admin/adminprofile.html')


# for showing result --->companies nearby
def result(request):
    company_list = CompanyDetail.objects.all().order_by('company_name')
    company_filter = CompanyFilter(request.GET, queryset=company_list)
    return render(request, 'deep_diagnose/company_list.html', {'filter': company_filter})


# gives list of all the companies
class CompanyList(generic.ListView):
    template_name = 'deep_diagnose/all_companies.html'
    context_object_name = 'all_companies'

    def get_queryset(self):
        return CompanyDetail.objects.all().order_by('company_name')


# gives details about the company->tests,price,contact info
class CompanyDetails(generic.DetailView):
    template_name = 'deep_diagnose/company_details.html'
    context_object_name = 'company'

    def get_queryset(self):
        return CompanyDetail.objects.all().order_by('test_name')


# delete company
class CompanyDelete(DeleteView):
    model = CompanyDetail
    success_url = reverse_lazy('deep_diagnose:adminhome')


# list of all tests
class TestList(generic.ListView):
    template_name = 'deep_diagnose/all_tests.html'
    context_object_name = 'all_tests'

    def get_queryset(self):
        return Tests.objects.all()


# gives details about selected test
class TestDetail(generic.DetailView):
    model = Tests
    template_name = 'deep_diagnose/test_detail.html'
    context_object_name = 'test'


# test categories
class Category(generic.DetailView):
    model = TestCategory
    template_name = 'deep_diagnose/category.html'
    context_object_name = 'category'


# use another test
class TestCreate(CreateView):
    model = Tests
    fields = ['test_name','category']
    success_url = reverse_lazy('deep_diagnose:adminhome')


# update existing test
class TestUpdate(UpdateView):
    model = Tests
    fields = ['test_name']
    success_url = reverse_lazy('deep_diagnose:adminhome')


# delete test
class TestDelete(DeleteView):
    model = Tests
    success_url = reverse_lazy('deep_diagnose:adminhome')


# returns company name on the basis search item in searchbox
def put_list(request):
    polls = Tests.objects.all()
    search_term=''
    if 'search' in request.GET:
        search_term = request.GET['search']
        polls = polls.filter(test_name__istartswith=search_term)

    context = {'search_term': search_term, 'polls': polls, }
    return render(request, 'deep_diagnose/searchresult.html', context)


def show_results(request, abc):
    # search=request.GET['search']
    polls = CompanyTests.objects.filter(tests__test_name=abc)
    """search_term = ''
    if 'search' in request.GET:
        search_term = request.GET['search']
        polls = polls.filter(test__icontains=search_term)"""

    context = {
        'polls': polls
    }
    return render(request, 'deep_diagnose/base.html', context)


# order the test
def OrderNow(request,pk):
    orderno=OrderInfo.objects.all().count()
    order = CompanyTests.objects.filter(id=pk)
    if request.method=='POST':
        p=OrderInfo()
        p.order_no=request.POST.get('orderno')
        p.company_name=request.POST.get('company_name')
        p.test_name=request.POST.get('test_name')
        p.user_name=request.POST.get('username')
        p.age=request.POST.get('age')
        p.email_id=request.POST.get('email_id')
        p.address_line_1=request.POST.get('address_line_1')
        p.city=request.POST.get('city')
        p.state=request.POST.get('state')
        p.country=request.POST.get('country')
        p.zip_code=request.POST.get('zip_code')
        p.phone_no=request.POST.get('phone_no')
        p.suitable_date=request.POST.get('suitable_date')
        p.suitable_time=request.POST.get('suitable_time')
        p.save()
        return render(request, 'deep_diagnose/thankyou.html',{'orders':orderno})
    else:
        return render(request,'deep_diagnose/ordernow.html',{'order':order,'orders':orderno})


def thankyou(request):
    return render(request, 'deep_Diagnose/thankyou.html')


# gives admin options to delete and update tests
class AdminTestList(generic.ListView):
    template_name = 'admin/admin_test_list.html'
    context_object_name = 'all_tests'

    def get_queryset(self):
        return Tests.objects.all().order_by('test_name')


# show list of companies and admin can delete it
class AdminCompanyList(generic.ListView):
    template_name = 'admin/admin_company_list.html'
    context_object_name = 'all_companies'

    def get_queryset(self):
        return CompanyDetail.objects.all().order_by('company_name')


@login_required
def profile(request):
    u_form = UserUpdateForm(request.POST, instance=request.user)
    p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

    if u_form.is_valid() and p_form.is_valid():
        u_form.save()
        p_form.save()

        def redirect_view(request):
            response = redirect('/profile/')
            return response
        # messages.success(request, f'Your Account has been updated')
        # return redirect('profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user)

    context = {'u_form': u_form, 'p_form': p_form}
    return render(request, 'deep_diagnose/profile.html', context)


def send(request):
    # send_mail('Subject here', 'Here is the message.', settings.EMAIL_HOST_USER,
    #           ['nshukl23@hmail.com'], fail_silently=False)
    # return render(request,'deep_diagnose/send.html')
    orderno = OrderInfo.objects.filter(username=User.username)
    return render(request,'deep_diagnose/send.html',{'orderno':orderno})


def OrderHistory(request):
    orders = OrderInfo.objects.filter(user_name=request.user)
    return render(request,'deep_diagnose/orderhistory.html',{'orders':orders})


class CancelOrder(DeleteView):
    model = OrderInfo
    success_url = reverse_lazy('deep_diagnose:orderhistory')


class OrderUpdate(UpdateView):
    model = OrderInfo
    fields = ['age','address_line_1','city','state','phone_no','zip_code','suitable_date',
              'suitable_time']
    success_url = reverse_lazy('deep_diagnose:adminhome')


def search_titles(request):
    context ={}
    if request.method == 'POST':
        search_text = request.POST['search_text']
        search = Tests.objects.filter(
            test_name__istartswith=search_text)
        context={
            'search':search,
        }
        html = render_to_string('deep_diagnose/search_results.html',context)

        return HttpResponse(html, content_type="application/json")
    return render(request,'deep_diagnose/ajax_search.html',context)

deep_diagnose/templates/deep_diagnose/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Deep Diagnose</title>
    <!--<link rel="stylesheet" href="bootstrap-4.1.3-dist/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- <link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/fixed.css"> -->

    <link rel="stylesheet" type="text/css" href="{% static 'deep_diagnose/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'deep_diagnose/css/fixed.css' %}">

    <script type="text/javascript" src="http://code.jquery.com/jquery-2.0.0.min.js"></script>
    <script type="text/javascript" src="/static/deep_diagnose/js/ajax.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <!--<meta charset="UTF-8">-->
    <!--<title>Title</title>-->
    {% block head %}
    {% endblock head %}
    <style>
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu .dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -1px;
}
</style>
</head>
{% block javascript %}
{% endblock javascript %}
<body data-spy="scroll" data-target="#navbarResponsive">
<!-- Start Home Section -->
<div id="home">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'deep_diagnose:find' %}"><img src="{% static 'deep_diagnose/img/logo.jpg' %}"> Deep Diagnose</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav">


                <li class="nav-item">
                    <div class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" style="color:white;">
                            TESTS
                        </a>
                        <ul class="dropdown-menu">
                            {% for test in testname %}
                            <li><a class="dropdown-item" href="{% url 'deep_diagnose:tests_detail' pk=test.id %}">{{ test.test_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <div class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" style="color:white;">
                            LABS
                        </a>
                        <ul class="dropdown-menu">
                            {% for lab in labsname %}
                            <li><a class="dropdown-item" href="{% url 'deep_diagnose:company_detail' pk=lab.id %}">{{ lab.company_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>



                <div class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" style="color:white;">
                        CATEGORY
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in cat %}
                        <li><a class="dropdown-item" href="{% url 'deep_diagnose:category' pk=category.id%}">{{ category.category }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="{% url 'logout' %}">LOGOUT</a>
                </li>
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="{% url 'deep_diagnose:profile' %}">{{ user.username }}</a>
                </li>
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="{% url 'deep_diagnose:orderhistory' %}">Order History</a>
                </li>
                {% else %}
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="{% url 'login' %}">USER</a>
                </li>
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="{% url 'deep_diagnose:register' %}">SIGNUP</a>
                </li>
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="{% url 'deep_diagnose:admin-login' %}">ADMIN</a>
                </li>
                <!--<li class="nav-item ml-auto">-->
                    <!--<a class="nav-link" href="{% url 'logout' %}">LOGOUT</a>-->
                <!--</li>-->
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

<br><br>


{% block body %}

{% endblock %}
<!-- End Navigation -->
<script src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
<script  src="{% static 'deep_diagnose/js/index.js' %}"></script>
<script>
$(document).ready(function(){
  $('.dropdown-submenu a.test').on("click", function(e){
    $(this).next('ul').toggle();
    e.stopPropagation();
    e.preventDefault();
  });
});
</script>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script src="{% static 'js/app.js' %}"></script>
<!--- End of Script Source Files -->
</body>
</html>

deep_diagnose/templates/deep_diagnose/base1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Deep Diagnose</title>
    <!--<link rel="stylesheet" href="bootstrap-4.1.3-dist/css/bootstrap.min.css">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- <link rel="stylesheet" href="css/style.css">
	<link rel="stylesheet" href="css/fixed.css"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'deep_diagnose/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'deep_diagnose/css/fixed.css' %}">

    <!--<meta charset="UTF-8">-->
    <!--<title>Title</title>-->

<body data-spy="scroll" data-target="#navbarResponsive">
<!-- Start Home Section -->
<br><br><br>
<h1>Admin</h1>
<div id="home">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="{% url 'deep_diagnose:adminhome' %}"><img src="{% static 'deep_diagnose/img/logo.jpg' %}"> Deep Diagnose</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link"href="{% url 'deep_diagnose:test-add' %}">
                        ADD TESTS
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link"href="{% url 'deep_diagnose:admin_test_list' %}">
                        ADMIN TEST LIST
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"href="{% url 'deep_diagnose:admin_company_list' %}">
                        ADMIN COMPANY LIST
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">LOGOUT</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'deep_diagnose:admin-profile' %}">{{ user.username }}</a>
                </li>





            </ul>
        </div>

    </nav>

</div>

{% block body %}

{% endblock %}
<!-- End Navigation -->
<script src="https://use.fontawesome.com/releases/v5.5.0/js/all.js"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>
<script  src="{% static 'deep_diagnose/js/index.js' %}"></script>
<!--- End of Script Source Files -->
</body>
</html>

deep_diagnose/templates/deep_diagnose/orderhistory.html
{% extends 'deep_diagnose/base.html' %}
{% block body %}
<div class="row">

    <div class="col-2" style="padding:35px;">
        <h3>Order No</h3>
    </div>
    <div class="col-3" style="padding:35px;">
        <h3>Company And Test</h3>
    </div>
    <div class="col-3" style="padding:35px;">
        <h3>Appointment Date</h3>
    </div>
    <div class="col-2" style="padding:35px;">

    </div>
</div>

{% for order in orders %}


<div class="row">

    <div class="col-2" style="padding:35px;">
        {{ order.order_no }}
    </div>
    <div class="col-3" style="padding:35px;">

        {{ order.company_name }}
        <br>
        {{ order.test_name }}

    </div>
    <div class="col-3" style="padding:35px;">

        {{ order.suitable_date }}
        <br>
        {{ order.suitable_time }}

    </div>
    <div class="col-1" style="padding:35px;">

        <form name="f1" method="POST" action="{% url 'deep_diagnose:cancel-order' order.pk %}">
            {% csrf_token %}<button type="submit" class="btn btn-default btn-sm">
            Cancel
        </button>
        </form>

    </div>
    <div class="col-1" style="padding:35px;">

        <form name="f1" method="POST" action="{% url 'deep_diagnose:update-order' order.pk %}">
            {% csrf_token %}<button type="submit" class="btn btn-default btn-sm">
            Update Info
        </button>
        </form>

    </div>
</div>

{% endfor %}
{% endblock %}

deep_diagnose/templates/deep_diagnose/search_results.html
<html>

<body>

<div class="table-responsive-sm pt-5 ml-5" >
    <table class="table" style="margin-left:15%;">

        <tbody>
        {% for i in search %}
        <tr class="row">

            <td class="col-lg-4"><h5>{{i.test_name}}</h5></td>
            <td class="col-lg-4 btn btn-success btn-sm"> <h5><a style="text-decoration: none; color:white;" href="{% url 'deep_diagnose:tests_detail' pk=i.pk %}">
                FIND COMPANIES
            </a></h5></td>


        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

</body>
</html>

deep_diagnose/templates/deep_diagnose/thankyou.html
<script>
        alert("Your order is placed");
        window.location.href = "/home/";
    </script>